### ISSUE TITLE
contact author of paper

### ISSUE THREAD

**Issue by ThomasWaldmann** [lichtkegel/aestools#11]
I think we should contact the author of the paper that triggered development of this tool.

Maybe the tool could be reviewed and also the author would know that there is code for his paper out there.

@lichtkegel can you do that? Maybe you could discuss it better.

**Comment by huettenhain** [comment]
Actually, he is here on github as @mjosaarinen.

**Comment by huettenhain** [comment]
I also wrote him an email and got a quick response. He said he gave the code a quick glance and didn't find anything wrong with it. He also emphasized again that this problem only applies to GCM. He pointed me to [a paper where the attack is generalized](https://eprint.iacr.org/2013/144.pdf), I will have a look at it later. From the abstract it doesn't seem to affect our code, it only makes the attack more usable. But that's only my first impression.

**Comment by huettenhain** [comment]
Guess I'll close this. If @mjosaarinen wants to have a closer look and finds anything, he can reopen the issue or create a new one.
