### ISSUE TITLE
expose strength determination via cli

### ISSUE THREAD

**Issue by ThomasWaldmann** [lichtkegel/aestools#17]
there is code for that, but one can't use it via the commandline yet.

**Comment by ThomasWaldmann** [comment]
well, #18 just makes it possible to give the threshold for check and get a binary answer ok / not ok.

i rather thought of actually displaying the strength of a checked or generated key in the output.

**Comment by larsborn** [comment]
so what do you suggest as the command line interface? --show-strength? Should we remove the --threshold again? I

**Comment by ThomasWaldmann** [comment]
just show it?
